FROM golang:1.21-bullseye as builder

WORKDIR /go

COPY ./tailscalex .

RUN CGO_ENABLED=0 go build -o bin/tailscalex main.go


FROM bitnami/kubectl:latest as kubectl

FROM hashicorp/vault:latest as vault

FROM gcr.io/distroless/base-debian11:debug-nonroot

COPY --from=builder /go/bin/tailscalex /usr/local/bin
COPY --from=kubectl /opt/bitnami/kubectl/bin/kubectl /usr/local/bin
COPY --from=vault /bin/vault /usr/local/bin
COPY rotate.sh entrypoint.sh .

ENTRYPOINT ["./entrypoint.sh"]

