FROM golang:1.21-bullseye as builder

WORKDIR /src

COPY ./tailscalex .

RUN CGO_ENABLED=0 go build -o bin/tailscalex main.go


FROM bitnami/kubectl:latest as kubectl

FROM hashicorp/vault:latest as vault

FROM gcr.io/distroless/base-debian11:debug-nonroot

LABEL org.opencontainers.image.source=https://github.com/ericz-home/home-ops

COPY --from=builder --chown=nonroot /src/bin/tailscalex /usr/local/bin/
COPY --from=kubectl --chown=nonroot /opt/bitnami/kubectl/bin/kubectl /usr/local/bin/
COPY --from=vault --chown=nonroot /bin/vault /usr/local/bin/
COPY --chown=nonroot rotate.sh entrypoint.sh .

ENTRYPOINT ["sh", "/home/nonroot/entrypoint.sh"]

