global:
  leaderElection:
    namespace: 'certmanager'

installCRDs: true

namespace: 'certmanager'

prometheus:
  enabled: false

podAnnotations:
  'match-regex.version-checker.io/cert-manager-controller': 'v(\d+)\.(\d+)\.(\d+)'

webhook:
  podAnnotations:
    'match-regex.version-checker.io/cert-manager-webhook': 'v(\d+)\.(\d+)\.(\d+)' 

cainjector:
  podAnnotations:
    'match-regex.version-checker.io/cert-manager-cainjector': 'v(\d+)\.(\d+)\.(\d+)'

clusterResourceNamespace: 'certmanager'

config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true
