global:
  leaderElection:
    namespace: 'certmanager'

installCRDs: true

namespace: 'certmanager'

prometheus:
  enabled: false

clusterResourceNamespace: 'cert-issuers'

config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true
