FROM golang:1.24-bullseye as builder

WORKDIR /src

COPY ./ .

RUN CGO_ENABLED=0 go build -o bin/homebot main.go bot.go config.go

FROM gcr.io/distroless/base-debian12:debug-nonroot

LABEL org.opencontainers.image.source=https://github.com/ericz-home/home-ops

COPY --from=builder --chown=nonroot /src/bin/homebot /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/homebot"]

