db:
  path: /data/diun.db

watch:
  workers: 5
  schedule: "0 */6 * * *"
  jitter: 30s
  runOnStartup: true

providers:
  kubernetes:
    watchByDefault: true

notif:
  discord:
    webhookURLFile: /vault/secrets/discord
    mentions:
      - "@Eric"
    renderFields: true
    timeout: 10s
    templateBody: |
      :whale: Docker Image  {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} as of {{ .Entry.Manifest.Created }}.
