db:
  path: /data/diun.db

watch:
  workers: 1
  schedule: "0 */6 * * *"
  jitter: 30s
  runOnStartup: true

defaults:
  watchRepo: true
  notifyOn:
    - new
    - update
  maxTags: 1
  sortTags: semver
  includeTags:
    - ^\d+\.\d+\.\d+$
    - ^v\d+\.\d+\.\d+$
    - stable
    - latest

providers:
  kubernetes:
    watchByDefault: true

notif:
  discord:
    webhookURLFile: /vault/secrets/discord
    renderFields: true
    timeout: 10s
    templateBody: |
      :whale: Docker Image  {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} as of {{ .Entry.Manifest.Created }}.
