name: Build

on:
  push:
    branches: ["main"]
    paths:
      - "tools/**"
      - ".github/workflows/**"

jobs:
  build-tailscalex:
    uses: ./.github/workflows/build_publish.yml
    permissions:
      packages: write
    with:
      image: ${{ github.repository_owner }}/tailscalex
      workdir: ./tools/tailscalex
    secrets: inherit
  build-mdns-proxy:
    uses: ./.github/workflows/build_publish.yml
    permissions:
      packages: write
    with:
      image: ${{ github.repository_owner }}/mdns-proxy
      workdir: ./tools/mdns-proxy
    secrets: inherit
  build-homebot:
    uses: ./.github/workflows/build_publish.yml
    permissions:
      packages: write
    with:
      image: ${{ github.repository_owner }}/homebot
      workdir: ./tools/homebot
    secrets: inherit
