name: Reusable Build and Publish

on:
  workflow_call:
    inputs:
      registry:
        default: ghcr.io
        required: false
        type: string
      workdir:
        default: .
        required: false
        type: string
      image:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        id: tag
        run: echo "TAG=${{ inputs.registry }}/${{ inputs.image }}:$(date +%Y-%m-%d)"
          >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.workdir }}
          push: true
          file: ${{ inputs.workdir }}/Containerfile
          tags: ${{ steps.tag.outputs.TAG }}

