name: Build

on:
  push:
    branches: ["main"]
    paths:
      - "toolbox/**"
      - ".github/workflows/**"

jobs:
  build-toolbox:
    uses: ./.github/workflows/build_publish.yml
    permissions:
      packages: write
    with:
      image: ${{ github.repository_owner }}/toolbox
      workdir: ./toolbox
    secrets: inherit
